export const UPDATE_TENANCY_INFO = "UPDATE_TENANCY_INFO";
export const UPDATE_TENANT_CONTACT_INFO = "UPDATE_TENANT_CONTACT_INFO";
export const UPDATE_TENANT_PERSONAL_INFO = "UPDATE_TENANT_PERSONAL_INFO";
export const UPDATE_PROPERTY_INFO = "UPDATE_PROPERTY_INFO";
export const UPDATE_LANDLORD_INFO = "UPDATE_LANDLORD_INFO";
